# Generated by Django 3.2.12 on 2022-02-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('type_name', models.CharField(max_length=256)),
                ('inches', models.FloatField()),
                ('resolution_w', models.PositiveIntegerField()),
                ('resolution_h', models.PositiveIntegerField()),
                ('cpu', models.CharField(max_length=256)),
                ('ram_gb', models.PositiveIntegerField()),
                ('mem1_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('FLASH', 'FLASH'), ('HYBRID', 'HYBRID')], max_length=16)),
                ('mem1_gb', models.PositiveIntegerField()),
                ('mem2_type', models.CharField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('FLASH', 'FLASH'), ('HYBRID', 'HYBRID')], max_length=16, null=True)),
                ('mem2_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('gpu', models.CharField(max_length=256)),
                ('os', models.CharField(blank=True, max_length=128, null=True)),
                ('weight_kg', models.FloatField()),
                ('price_euro', models.FloatField()),
                ('stock_amnt', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'laptops',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laptops_store.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price_euro', models.FloatField()),
                ('amnt', models.PositiveIntegerField()),
                ('laptop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laptops_store.laptop')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops_store.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_laptops',
            field=models.ManyToManyField(through='laptops_store.OrderItem', to='laptops_store.Laptop'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laptops_store.manufacturer'),
        ),
    ]
