# Generated by Django 3.2.12 on 2022-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='mem1_gb',
            new_name='mem_flash_gb',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='mem1_type',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='mem2_gb',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='mem2_type',
        ),
        migrations.AddField(
            model_name='laptop',
            name='mem_hdd_gb',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='mem_hybrid_gb',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='mem_ssd_gb',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
