# Generated by Django 3.2.12 on 2022-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops_store', '0003_auto_20220223_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='mem_flash_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='mem_hdd_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='mem_hybrid_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='mem_ssd_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
