# Generated by Django 3.2.12 on 2022-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops_store', '0004_auto_20220223_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
