# Generated by Django 3.2.12 on 2022-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops_store', '0005_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
